---
apiVersion: v1
kind: Pod
metadata:
  name: nginxcontainer
spec: 
  containers:
    - image: nginx
      name: nginximage
      ports:
        - containerPort: 80
          protocol: TCP
    - image: jenkins/jenkins:jdk11
      name: jenkins
      ports:
        - containerPort: 8080
          protocol: TCP