---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: db-deploy
spec:
  minReadySeconds: 3
  replicas: 1
  selector:
    app: postgres
    matchLabels:
      app: postgres
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
        version: "13"
    spec:
      containers:
        - name: postgres
          image: postgres:13-alpine
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
           - mountPath: /var/lib/mysql
             name: gp2
    volumes:
    - name: postgres
      persistentVolumeClaim:
        claimName: gp2
        readOnly: false 
