---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: db-deploy
spec:
  minReadySeconds: 3
  replicas: 1
  selector:
    app: redis
    matchLabels:
      app: redis
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: redis
      labels:
        app: redis
        version: "5.0"
    spec:
      containers:
        - name: redis
          image: redis:5.0-alpine
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
           - mountPath: /var/lib/redis
             name: gp2
    volumes:
    - name: redis
      persistentVolumeClaim:
        claimName: gp2
        readOnly: false 