---
pool: 
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-latest'

trigger:
  - master

stages:
- stage: dockerinstall
  jobs:
  - job: installjob 
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: mydocker
        repository: kishorekrrish/github
        command: 'buildAndPush' 
        Dockerfile: '**/Dockerfile'
    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'dockerimage'
        path: "$(Build.ArtifactStagingDirectory)" 
