---
- name: installing java from tar file
  hosts: all
  become: true
  tasks:
    - name: install java package
      ansible.builtin.unarchive:
        src: https://download.java.net/java/GA/jdk13.0.1/cec27d702aa74d5a8630c65ae61e4305/9/GPL/openjdk-13.0.1_linux-x64_bin.tar.gz
        remote_src: true
        dest: /root
    - name: Add a line to bashrc
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: "{{ item }}"
      with_items:
      - 'JAVA_HOME=/root/jdk-13.0.1'
      - 'export JAVA_HOME'
      - 'export PATH=$PATH:$JAVA_HOME/bin'
    - name: Source the file
      ansible.builtin.shell: source /root/.bashrc
      args:
        executable: /bin/bash
