---
- name: installing nginx
  hosts: all
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        update_cache: true
        state: present
    - name: copy service file
      ansible.builtin.copy:
        src: default
        dest: /etc/nginx/sites-available/default
    - name: start nginx service
      ansible.builtin.systemd:
        name: nginx 
        enabled: yes
        state: started
      