---
- name: install lampstack
  become: yes
  hosts: all
  tasks:
    - name: install apache2 and update paacakges
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
    - name: install php
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
    - name: create file
      ansible.builtin.file:
        path: /var/www/html/info.php
        state: touch
    - name: copythefiles
      ansible.builtin.copy:
        dest: /var/www/html/info.php
        content: |
          <?php
             phpinfo();
          ?>  