---
- name: install apache2 on ubuntu
  hosts: ubuntu
  become: true
  tasks:
    - name: install apache2 
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present

---
- name: install httpd on centos
  hosts: all
  become: true
  tasks:
    - name: install httpd
      ansible.builtin.yum:
        name: httpd
        update_cache: yes
        state: present
    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: httpd
        state: started

      
---
- name: installing nginx on ubuntu
  hosts: all
  become: true
  tasks: 
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        update_cache: true
        state: present


