---
- name: installing ha proxy
  hosts: haproxy
  become: true
  tasks:
    - name: install haproxy
      ansible.builtin.apt:
        name: haproxy
        update_cache: yes
        state: present
    - name: adding haproxy
      ansible.builtin.group:
        name: haproxy
        state: present
    - name: adding haproxy
      ansible.builtin.user:
        name: haproxy
        create_home: true
        group: haproxy
        state: present
    - name: change permissions
      ansible.builtin.file:
        path: /etc/haproxy
        recurse: yes
        owner: haproxy
        group: haproxy
        state: directory
        mode: '0777'
    - name: copy configuration files
      ansible.builtin.copy:
        src: /etc/haproxy/haproxy.cfg
        remote_src: true
        dest: /etc/haproxy/haproxy.cfg.bk
        owner: haproxy
        group: haproxy
    - name: Copy config
      ansible.builtin.copy:
        src: haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: haproxy
        group: haproxy
    - name: restart haproxy
      ansible.builtin.systemd:
        name: haproxy
        daemon_reload: true
        enabled: true
        state: restarted