---
pool:
  name: "kishore"

trigger:
  - main

steps:
- script: |
    ansible-playbook -i hosts spring.yml
  workingDirectory: /home/kishore
  displayName: my playbook to install spring pet clinic application