---
- name: instlling spring pet clinic application
  hosts: all
  become: true
  tasks:
    - name: install java
      ansible.builtin.apt:
        name: openjdk-17-jdk 
        state: present
    - name: download jar file
      ansible.builtin.get_url:
        url: https://krrish387.s3.ap-south-1.amazonaws.com/spring-petclinic-3.0.0-SNAPSHOT.jar
        dest: /home/ubuntu
        mode: '0777'
    - name: copying service file
      ansible.builtin.copy:
          src: spring.service
          dest: /etc/systemd/system/spring.service
          mode: '0777'
    - name: start services
      ansible.builtin.systemd:
          name: spring.service
          daemon_reload: true
          enabled: true
          state: started