---
hosts: all
become: true
tasks:
  - name: install java
    ansible.builtin.apt:
      name: openjdk-17-jdk 
      state: present



---
pool:
  name: "kishore"
  vmImage: ubuntu-latest
trigger:
  - main

strategy:
  matrix:
    Python37:
      python.version: '3.7'
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'
    Python310:
      python.version: '3.10'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'python version'
  
  - script: pip install ansible[azure]
    displayName: 'Install Ansible and the Azure modules'

  - script: ansible-playbook -i inv site.yml
    displayName: 'Run Ansible Playbook'

    