---
pool:
  name: "Azure Pipelines"
  vmImage: ubuntu-latest

trigger:
  - main

strategy:
  matrix:
    Python37:
      python.version: '3.7'
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'
    Python310:
      python.version: '3.10'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'python version'
  - script: |
      mv hello.py app.py
      pip3 install flask
    displayName: 'Install dependencies'
  - script: |
      flask run -h "0.0.0.0"
    displayName: 'run application'    
  