---
- name: install jenkins on ubuntu
  hosts: all
  become: true
  tasks:
    - name: java install
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: true
        state: present
    - name: download jenkins file
      ansible.builtin.get_url:
        url: https://updates.jenkins.io/download/war/2.385/jenkins.war
        dest: /home/ubuntu
        mode: '0777'
    - name: copy content to jenkins service file
      ansible.builtin.copy:
        src: jenkins.service
        dest: /lib/systemd/system/jenkins.service
    - name: start jenkins
      ansible.builtin.systemd:
        name: jenkins.service
        daemon_reload: yes
        enabled: yes
        state: started